// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1s_AFD6SZ098OAAUYn2y1JcYPk-O_RVU',
    appId: '1:975804419773:web:d7dad28b7cd7711f4571d4',
    messagingSenderId: '975804419773',
    projectId: 'loginapp-e2ef9',
    authDomain: 'loginapp-e2ef9.firebaseapp.com',
    storageBucket: 'loginapp-e2ef9.appspot.com',
    measurementId: 'G-GPG69S8LWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJD0flMJJ_tp1FCLiuqEMaBUQZSOwQkew',
    appId: '1:975804419773:android:d456fbc39cbad67d4571d4',
    messagingSenderId: '975804419773',
    projectId: 'loginapp-e2ef9',
    storageBucket: 'loginapp-e2ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdYuBre2Rzfi1cuOSQvIrUDr4wdPNCDI',
    appId: '1:975804419773:ios:a74ae233772799144571d4',
    messagingSenderId: '975804419773',
    projectId: 'loginapp-e2ef9',
    storageBucket: 'loginapp-e2ef9.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgdYuBre2Rzfi1cuOSQvIrUDr4wdPNCDI',
    appId: '1:975804419773:ios:a74ae233772799144571d4',
    messagingSenderId: '975804419773',
    projectId: 'loginapp-e2ef9',
    storageBucket: 'loginapp-e2ef9.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1s_AFD6SZ098OAAUYn2y1JcYPk-O_RVU',
    appId: '1:975804419773:web:f78245d5dc44201f4571d4',
    messagingSenderId: '975804419773',
    projectId: 'loginapp-e2ef9',
    authDomain: 'loginapp-e2ef9.firebaseapp.com',
    storageBucket: 'loginapp-e2ef9.appspot.com',
    measurementId: 'G-2Q2CCZG33K',
  );
}
